- name: Add the hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - add_host:
        name: shadowsocks
        groups: aws
        ansible_user: ubuntu
        ansible_host: "{{ aws_shadowsocks_host_ip.value if aws_shadowsocks_host_ip is defined else host_ip }}"
        ansible_ssh_private_key_file: "{{ aws_shadowsocks_ssh_key_file.value if aws_shadowsocks_ssh_key_file is defined else ssh_key }}"

- name: "Install Python and Systemd"
  hosts: aws
  become: True
  gather_facts: no
  pre_tasks:
    - name: Install Python
      raw: sudo apt-get -y install python

  tasks:
    - name: Install systemd packages
      apt:
        name: systemd
        update_cache: yes

- name: "Install Docker CE"
  hosts: aws
  become: True
  vars:
    docker_edition: ce
    docker_channel: stable
    docker_install_docker_compose: True
    docker_version: "18.03.0"

  roles:
    - { role: "nickjj.docker", tags: "docker" }

- name: Install Ansible Docker Service Required Packages
  hosts: aws
  gather_facts: no
  become: true
  tasks:
    - name: Update APT Cache
      apt: update_cache=yes

    - name: Install APT Packages
      apt:
        name: "{{ item }}"
      with_items:
        - python-pip

    - name: Uninstall old Packages
      pip:
        state: absent
        name:
          - docker
          - docker-py
          - docker-compose

    - name: Install PIP Packages
      pip:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
      with_items:
        - name: docker
          version: 3.2.1
        - name: docker-compose
          version: 1.15.0
